### ISSUE TITLE
v2.0.0 Release Notes

### ISSUE THREAD

**Issue by geek** [joyent/node-piloted#11]
## Summary

Version 2.0.0 includes a few enhancements and one breaking change. The API is changed from calling `Piloted()` directly to access the next service to explicitly calling `Piloted.service()`. Additionally, there is now support for events as well as loading configuration from the `CONTAINERPILOT` environment variable.

## Upgrade Steps

Search and replace any call to `Piloted(name)` with `Piloted.service(name)`

## Enhancements

- `refresh` event is added, which is triggered whenever the configuration is reloaded from a direct call to `refresh` or from a `SIGHUP` signal being sent to the process
- configuration is now automatically loaded if the `CONTAINERPILOT` environment variable is set

**Comment by deitch** [comment]
FYI, the `class`-driven `Piloted` combined with automatic config-loading on `CONTAINERPILOT` env var just made even my simple use cases _much_ cleaner!
