### ISSUE TITLE
How do dependent services update?

### ISSUE THREAD

**Issue by deitch** [joyent/node-piloted#6]
This is a great module, simplifies the pattern.

But, how do dependent modules work? E.g. you are connecting to redis. You create a client. You don't do it on each request, such that you could ask `piloted` for the address with each request. Setting up a connection (like with SQL databases) is expensive.

Instead, you create a connection once and reuse it (and with DBs, a connection pool). 

There is a need for an event (or handler) to say, "new config, please refresh yourself".

E.g. we do *not* do:

````javascript
var rclient;
Piloted.config(ContainerPilot, (err) => {
        app.get('/path', (req,res,next) => {
   	    const rservice = Piloted('redis');
	    rclient = redis.createClient(rservice.port, rservice.address);
        });
});

(similarly for RDBMS)

Instead, we do early setup:

````javascript
var rclient;
Piloted.config(ContainerPilot, (err) => {
	const rservice = Piloted('redis');
	rclient = redis.createClient(rservice.port, rservice.address);
       // do lots of stuff
});
````

But now if there is an update, we do not know it, and `rclient` fails out.

Possible alternative:

````javascript
Piloted.on('refresh', () => {
      	rclient = redis.createClient(rservice.port, rservice.address);
});    
````

**Comment by geek** [comment]
@deitch agreed. I discovered this issue when updating the following example: https://github.com/autopilotpattern/nodejs-example/blob/master/temperature/lib/index.js#L85

`refresh` or `update` makes sense

**Comment by deitch** [comment]
I just forked it, happy to do a PR, if you want.

**Comment by deitch** [comment]
BTW, one "glitch": because it returns a function, but the methods are on the object as well, you cannot just `extends EventEmitter`, you need to decorate it.

**Comment by deitch** [comment]
Works, and passes tests. If I submit the PR, will it get pulled?

**Comment by geek** [comment]
@deitch happy to review

**Comment by deitch** [comment]
How did you get _that_ GitHub handle, @geek? :-) 

Submitting now...

**Comment by deitch** [comment]
There you go.

**Comment by geek** [comment]
@deitch thanks for the help. I got the name by emailing support ;)
