### ISSUE TITLE
Did you build a golang equivalent, sort of go-piloted?

### ISSUE THREAD

**Issue by deitch** [joyent/node-piloted#8]
Could be useful there as well

**Comment by geek** [comment]
Not at the moment, but it's a great idea. I would be happy to support anyone who creates one ;)

Closing for now, but will link to any go-piloted that is created.

**Comment by deitch** [comment]
I might have a prototype. I needed something for a sample app built in go, so put it in. Largely follows the same pattern/style. I will try to extract and publish.

**Comment by deitch** [comment]
Got something going, will push to GitHub soon. Need to get proper test harness in place.

**Comment by deitch** [comment]
Here you go, just because I am such a nice guy (ok, maybe because it was a fun little piece of work....). Took much longer to write the tests than the lib. Isn't it always that way?

https://github.com/deitch/gopiloted
